apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: my-custom-builder
  namespace: default
spec:
  serviceAccount: default
  tag: registry.default.svc.cluster.local:5001/custom-builder
  stack: bionic-stack
  store: sample-store
  order:
  - group:
    - id: org.cloudfoundry.node-engine
    - id: org.cloudfoundry.yarn
  - group:
    - id: org.cloudfoundry.node-engine
    - id: org.cloudfoundry.npm  
