name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install node dependencies
      run: |
        pushd ui
        npm install
    - name: run linter
      run: |
        pushd ui
        npm run lint
    - name: run tests
      run: |
        pushd ui
        npm run
