name: CI

on: [push]

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install node dependencies
      run: |
        pushd web
        npm install
    - name: run linter
      run: |
        pushd web
        npm run lint
    - name: run tests
      run: |
        pushd web
        npm run test
  test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: install opengl
      run: sudo apt install libgl1-mesa-dev xorg-dev
    - name: Run tests
      run: go test -v ./...
